image: library/alpine

pages:

  tags:
    - shared
    - gitlab-pages
    - docker

  before_script:
    - apk update
    - apk add --no-cache nodejs
    - apk add --no-cache npm
    - node --version
    - npm install jsdoc -g
    - apk add maven

  script:
    - echo "Building Site using Docker Executor"
    - mkdir .public
    - ls src/main/resources/static/wica/*
    - jsdoc src/main/resources/static/wica/* -c src/main/resources/static/wica/conf.json -d .public/js
    - ls .public/js/wica
    - which java
    - mvn javadoc:javadoc
    - ls target/site/apidocs
    - mv target/site/apidocs .public/java/
    - ls .public/js/java
    - mv .public public
    - ls public/wica

  artifacts:
    paths:
      - public

  only:
    - master

