image: library/alpine

before_script:
  - apk update
  - apk add --no-cache nodejs
  - node version

pages:

  tags:
    - shared
    - gitlab-pages
    - docker

  script:
    - echo "Building Site using Docker Executor"
    - mkdir .public
    - jsdoc src/main/resources/static/wica/* -c src/main/resources/static/wica/conf.json -d .public
    - mv .public public
    -
  artifacts:
    paths:
      - public

  only:
    - master

