image: gliderlabs/alpine

before_script:
  - apk --update add node
  - node version

pages:
  script:
    - echo "Building Site using Docker Executor"
    - mkdir .public
    - jsdoc src/main/resources/static/wica/* -c src/main/resources/static/wica/conf.json -d .public
    - mv .public public
  tags:
    - shared
    - gitlab-pages
    - docker
  artifacts:
    paths:
      - public
  only:
    - master

