image: library/alpine

pages:

  tags:
    - shared
    - gitlab-pages
    - docker

  before_script:
    - apk update
    - apk add --no-cache nodejs
    - apk add --no-cache npm
    - node --version
    - npm install jsdoc -g

  script:
    - echo "Building Site using Docker Executor"
    - mkdir .public
    - ls src/main/resources/static/wica/*
    - jsdoc src/main/resources/static/wica/* -c src/main/resources/static/wica/conf.json -d .public
    - ls .public/wica
    - mv .public public
    - ls public/wica

  artifacts:
    paths:
      - public

  only:
    - master

