language: java

jdk:
  - openjdk11

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - echo -n "*** LIFECYCLE STARTED - 'before_install' *****************************************************************"
  - echo -n "*** LIFECYCLE COMPLETED - before_install *****************************************************************"

# Note: 'Install' here means things into the Travis environment that are needed.
install:
  - echo "*** LIFECYCLE STARTED - 'install' ***************************************************************************"
  - echo "*** LIFECYCLE COMPLETED - 'install' *************************************************************************"

# Build the code then build the javadoc.
before_script:
  - echo -n "*** LIFECYCLE STARTED - 'before_script' ******************************************************************"
  - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#  - mvn javadoc:javadoc -B -V
  - echo -n "*** LIFECYCLE COMPLETED - 'before_script' ****************************************************************"

# Used here to upload the docker file to Docker Hub.
script:
  - echo -n "*** LIFECYCLE STARTED - 'script' *************************************************************************"
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#  - docker build -t paulscherrerinstitute/wica-stream:latest -f docker/Dockerfile.http .
#  - docker push paulscherrerinstitute/wica-stream:latest
#  - echo -n "LIFECYCLE COMPLETED - 'script' ***************************************************************************"

# The deploy phase is optional and runs after the script. Here we use it to publish
# the Javadoc on the GitHub pages site.
deploy:
  provider: releases
  api_key:
    secure: "lXM2RtmKUW4FDkHpKSNlz3/+AoTao2J9eTpiXJalxM7Gaosj9/ehVsZgUkxf/KQupsaZwwP1yKetgSlEpSq+qVlDleAlY44lerJ598mo/vgwKlxw8Xqq8lKzVnumOI0nw3U+9RPQFtAIbxnriHhLTDoV6sujNB2obnhxqju8NcTfmXiKUkWpiYWlLUzZ3gHk52fHatQAG1FGjpLUl0Un8Rez1Nc2QJet2WbkYdvmyKUS/xza0tUjn4ctdS/OwnEz0LzP6Mnn88rzl1gtoZDJFOP3LHN2Ob0EY3Ts31mcvoOMChgJ60EhyOTW0AAxIuGcaA/bTIuYV4Hnq8ACeXz2Hcc4UxxiRUgCReyDsbuvZBndf75q8/Ym/AHvMDYo4iydKHcCTOjLg18RT7SGItpHuhdpGIH8sOflz3bE2YnDpls1TvM+6uTC0+g3nX2m+g6zU4z4OI4Opmo9zvMiWNUILWgu+h2LXleK7yq+CO2eeiByKr1PlBeHAiy+JBJ2P/d0G81LWxmXYvQvPaYQCbDHmJTcKvsKewSjivTDsJVF3w+/guUPGAvUhN15dLH9CzHQevGTXW84a5Tx/SJkCZ0ubFnLbnpBRwepYRr9dkp5ZhEbipUio4w/KJqOhmJEGtchjPshtL5W04NN4/4zV5wF4cEMnPJQ8jAR2X9vU3A/+rs="
  file: target/wica-http-1.0.0-RELEASE.jar
  skip_cleanup: true
  draft: true
  on:
    repo: paulscherrerinstitute/wica-http

#  provider: pages
#  local_dir: $TRAVIS_BUILD_DIR/target/site/apidocs
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#  keep_history: true
#  on:
#    branch: master


after_script:
  - echo -n "*** LIFECYCLE STARTED - 'after_script' *******************************************************************"
  - echo -n "*** LIFECYCLE COMPLETED - 'after_script' *****************************************************************"

