language: java

jdk:
  - openjdk11

services:
  - docker

before_install:
  - echo -n "*** LIFECYCLE STARTED - 'before_install' *****************************************************************"
  - echo -n "*** LIFECYCLE COMPLETED - before_install *****************************************************************"

install:
  - echo "*** LIFECYCLE STARTED - 'install' ***************************************************************************"
  - echo "*** LIFECYCLE COMPLETED - 'install' *************************************************************************"

before_script:
  - echo -n "*** LIFECYCLE STARTED - 'before_script' ******************************************************************"
  - mvn package -DskipTests=true -B -V
  - echo -n "*** LIFECYCLE COMPLETED - 'before_script' ****************************************************************"

script:
  - echo -n "*** LIFECYCLE STARTED - 'script' *************************************************************************"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t paulscherrerinstitute/wica-stream:latest -f docker/Dockerfile.http .
  - docker push paulscherrerinstitute/wica-stream:latest
  - echo -n "LIFECYCLE COMPLETED - 'script' ***************************************************************************"

deploy:
  provider: pages
  local_dir: target/site/apidocs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

after_script:
  - echo -n "*** LIFECYCLE STARTED - 'after_script' *******************************************************************"
  - echo -n "*** LIFECYCLE COMPLETED - 'after_script' *****************************************************************"

